# Generated by Django 4.2.4 on 2023-09-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DecoyOps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='surname',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
